# Use powerline
USE_POWERLINE="true"
# Has weird character width
# Example:
#    is not a diamond
HAS_WIDECHARS="false"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi

# Add settings scripts to PATH
export PATH="$HOME/settings/scripts:$PATH"

# Phone helpers
alias sync-music='rsync -avh --progress ~/Music/ ~/phone/Internal\ storage/Music/'

# User scripts management alias
alias scripts="~/settings/scripts/manage-user-scripts.sh"
