#! /bin/bash

# проверяем на наличие аргумента
# если нет аргумента запрашиваем его
# аргумент - имя скрипта
[ $1 ] && nameFile=$1 || read -r -p "Enter name script: " nameFile

# если скрипт существует то открываем скрипт для редактирования
# иначе создаем скрипт

# директория для запуска скриптов $PATH
dir_basic=/home/vitaliy/settings/scripts

cd $dir_basic

# проверка на наличие скриптa с таким именем 
if [ ! -f $nameFile ];then
    # создаем файл с shebang и даем права на запуск
    echo "#! /bin/bash" > $nameFile
    chmod +x $nameFile

    # Открываем файл скрипта
    vim $nameFile
else
    # Открываем файл скрипта
    vim $nameFile
fi

